# Generated by Django 3.1.1 on 2020-10-24 02:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_auto_20201023_2146'),
    ]

    operations = [
        migrations.AlterField(
            model_name='marcas',
            name='name',
            field=models.CharField(max_length=50, verbose_name='Nombre de la Marca'),
        ),
    ]
