# Generated by Django 3.1.1 on 2020-10-24 02:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_auto_20201023_2148'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='name',
            field=models.CharField(max_length=100, verbose_name='Nombre Categoría'),
        ),
        migrations.AlterField(
            model_name='marcas',
            name='name',
            field=models.CharField(max_length=100, verbose_name='Nombre de la Marca'),
        ),
        migrations.AlterField(
            model_name='subcategory',
            name='name',
            field=models.CharField(max_length=100, verbose_name='Nombre Subcategoría'),
        ),
    ]
