# Generated by Django 3.1.1 on 2020-10-27 03:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0008_auto_20201025_1909'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='marca',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='marca_id', to='products.marcas', verbose_name='Marcas del producto'),
        ),
    ]
