# Generated by Django 3.1.4 on 2021-01-26 02:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0008_auto_20210105_2248'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='before',
            field=models.DecimalField(blank=True, decimal_places=2, default=None, max_digits=9, verbose_name='Precio anterior'),
        ),
        migrations.AlterField(
            model_name='product',
            name='descripcion',
            field=models.TextField(verbose_name='Descripcion'),
        ),
    ]
