# Generated by Django 3.1.1 on 2020-10-28 03:38

from django.db import migrations
import django.db.models.manager


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0009_auto_20201026_2227'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='product',
            managers=[
                ('objectProduct', django.db.models.manager.Manager()),
            ],
        ),
    ]
