# Generated by Django 3.1.4 on 2021-01-26 02:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0009_auto_20210125_2138'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='before',
            field=models.DecimalField(decimal_places=2, default=None, max_digits=9, null=True, verbose_name='Precio anterior'),
        ),
    ]
