# Generated by Django 3.1.4 on 2021-01-26 02:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0010_auto_20210125_2144'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='before',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=9, null=True, verbose_name='Precio anterior'),
        ),
    ]
