# Generated by Django 3.1.3 on 2020-11-22 03:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0012_auto_20201121_2244'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='thumbnail',
            field=models.ImageField(blank=True, upload_to='media/thumbnail/', verbose_name='Imagen Principal'),
        ),
    ]
