# Generated by Django 3.1.3 on 2020-11-24 03:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0014_auto_20201121_2322'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='before',
            field=models.DecimalField(blank=True, decimal_places=2, default=123, max_digits=9, verbose_name='Precio'),
            preserve_default=False,
        ),
    ]
