# Generated by Django 3.1.3 on 2021-01-06 03:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0002_auto_20210105_2110'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cartitem',
            name='count',
            field=models.PositiveIntegerField(),
        ),
    ]
