# Generated by Django 3.1.3 on 2021-02-02 03:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0004_auto_20210201_2254'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='cartitem',
            options={'ordering': ['-created']},
        ),
    ]
